---
title: "crg_co_mutation"
author: "Kexin Dong"
date: "`r Sys.Date()`"
output: html_document
---
# Package Loading
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Automatic wraps of coding chunks
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=55),tidy=TRUE)

# Automatic wraps of outputs
new.printLongLine <- function(a)
{
  len <- nchar(a)
  linelen <- 80
  lineNumber <- ceiling(len / linelen)
  index <- 0
  repeat
  {
    if(index + 1 == lineNumber)
    {
      cat(substring(a, index * linelen + 1, len))
      break
    }
    cat(substring(a, index * linelen + 1, index * linelen + linelen))
    cat('\n')
    index <- index + 1
  }
}
```

```{r,include = FALSE}
# load packages
# Package names
packages <- c("jpeg","lars","glmnet","xlsx", "ggplot2", "dplyr", "cometExactTest", "stringr", "maditr", "reshape2", "data.table", "epitools", "corrplot", "plyr", "muhaz", "reshape", "survival", "survivalAnalysis", "survMisc", "survminer", "ggsci", "vegan", "ggrepel", "ggforce", "rstatix", "effsize", "psych", "maxstat", "RCurl", "ggpubr", "UpSetR", "cowplot", "readxl", "scales", "rlist", "ggplotify", "ggridges", "gridExtra", "BradleyTerry2","ggthemes","patchwork","pheatmap","UpSetR","knitr","kableExtra","VennDiagram","ComplexHeatmap","circlize","ggplot2", "dplyr", "cometExactTest", "stringr", "maditr", "reshape2", "data.table", "epitools", "corrplot", "plyr", "muhaz", "reshape", "survival", "survivalAnalysis", "survMisc", "survminer", "ggsci", "vegan", "ggrepel", "ggforce", "rstatix", "effsize", "psych", "devtools","RColorBrewer")

# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

# Packages loading
invisible(lapply(packages, library, character.only = TRUE))
```

# Set Directory
```{r}
# setwd("/Users/gorkordkx/Documents/GitHub/H2M-py")
```

# Coor Plot of the AA change coverage
```{r}
freq_genes_matrix_hr <- read.csv('.../Output/IDR/df_wide.csv')
freq_genes_matrix_q <- read.csv('.../Output/IDR/df_wide_sig.csv')

rownames(freq_genes_matrix_hr) <- freq_genes_matrix_hr[, 1]
freq_genes_matrix_hr <- freq_genes_matrix_hr[, -1]

freq_genes_matrix_hr[is.na(freq_genes_matrix_hr)] <- 0
freq_genes_matrix_hr = as.matrix(freq_genes_matrix_hr)
freq_genes_matrix_hr = t(freq_genes_matrix_hr)
#   freq_genes_matrix_hr[freq_genes_matrix_hr > 0.8] <- 0.8

rownames(freq_genes_matrix_q) <- freq_genes_matrix_q[, 1]
freq_genes_matrix_q <- freq_genes_matrix_q[, -1]

freq_genes_matrix_q[is.na(freq_genes_matrix_q)] <- 0
freq_genes_matrix_q = as.matrix(freq_genes_matrix_q)
freq_genes_matrix_q = t(freq_genes_matrix_q)
 
pdf(file = "corr_group.pdf", width = 4, height = 4)
corrplot(freq_genes_matrix_hr,col = COL1('YlGn',6), p.mat = freq_genes_matrix_q, sig.level = 0.01, col.lim = c(0, 2.4), is.corr = F, method = 'color', tl.col="black", pch.col = "grey50", pch.cex = 0.5,addgrid.col = 'white') 
dev.off()
```

# Corr plot of predicted epitope representation score  

```{r}
model <- lm(score_h ~ score_m, data = df_freq)
summary_model <- summary(model)
slope <- summary_model$coefficients["score_m", "Estimate"]
intercept <- summary_model$coefficients["(Intercept)", "Estimate"]
title_text <- sprintf("y = %.2fx + %.2f", slope, intercept)

pearson_cor <- cor(df_freq$score_m, df_freq$score_h, method = "pearson")
title_text <- sprintf("Pearson Correlation: r = %.2f", pearson_cor)
```


```{r}
df_freq <- read.csv('.../mhc_result_rank_top.csv')
# p1 = 
element1 <- "MHC-I" 
element2 <- "MHC-II" 


vector1 <- rep(element1, 7) 
vector2 <- rep(element2, 36) 
df_freq$color <- c(vector1, vector2)

p1 =  ggplot(df_freq, aes(x=score_m, y=score_h))+
    geom_smooth(method='lm',  formula = 'y ~ x', size = 1.5, color = 'grey', se = T)+
  theme_cowplot() +
  # geom_hline(yintercept=1.30103, linetype="dashed", color = "#d9d9d9") +
  geom_point(aes(color = color), alpha = .75,  size = 5) +
    geom_label_repel(aes(label=label_name, color = observed),nudge_y = .1, size = 3, force = 25, max.overlaps = 5)+
  scale_colour_manual(values = c('MHC-I'='#92BFB1','MHC-II'='#A61C3C', 'Yes' = 'grey','No' = 'green')) + 
  theme(legend.position = c(0.05,.85)) +
  ylab(label= "Human Epitope Score") +
  xlab(label= "Mouse Epitope Score") +
  xlim(0,1.5)+
  ylim(0,1.5)+
  scale_x_continuous(breaks = seq(0,1, by = .25)) + 
  scale_y_continuous(breaks = seq(0,1, by = .25))+
    labs(title = title_text)
  
  ggsave(filename = "/Users/gorkordkx/Documents/Output/h2m/neoantigen/mhc_result_rank_2.svg", p1,  width = 5, height = 5, units = "in")
```









